config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [ :index ]

  get '/redirect', to: 'calendars#redirect', as: 'redirect'
  get '/callback', to: 'calendars#callback', as: 'callback'
  get '/events', to: 'calendars#events', as: 'events'

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/token.rb
class Token < ActiveRecord::Base
  def to_params
    { 'refresh_token' => refresh_token,
      'client_id'     => ENV['GOOGLE_CLIENT_ID'],
      'client_secret' => ENV['GOOGLE_CLIENT_SECRET'],
      'grant_type'    => 'refresh_token'}
  end

  def request_token_from_google
    url = URI("https://accounts.google.com/o/oauth2/token")
    Net::HTTP.post_form(url, self.to_params)
  end

  def refresh!
    data = JSON.parse(request_token_from_google.body)
    update_attributes(
        token: data['access_token'],
        expires_at: Time.now + data['expires_in'].to_i.seconds
    )
  end

  def self.access_token
    #convenience method to retrieve the latest token and refresh if necessary
    t = Token.last
    t.refresh! if t.expires_at < Time.now
    t.token
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, unless: :home_controller?

  before_action :configure_devise_permitted_parameters, if: :devise_controller?


  private
    # Overwriting the sign_out redirect path method
    def after_sign_out_path_for(resource_or_scope)
      root_path
    end

    def after_sign_in_path_for(resource)
      redirect_path
      # request.env['omniauth.origin'] || stored_location_for(resource) || redirect_path
    end

    def after_sign_up_path_for(resource)
      redirect_path
      # request.env['omniauth.origin'] || stored_location_for(resource) || redirect_path
    end

  protected

    def configure_devise_permitted_parameters
      registration_params = [ :email, :password, :password_confirmation ]

      if params[:action] == 'update'
        devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(registration_params << :current_password) }
      elsif params[:action] == 'create'
        devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(registration_params) }
      end
    end

    def home_controller?
      controller_name == 'home'
    end

end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_action :set_client

  def redirect
    redirect_to @client.authorization_uri.to_s
  end

  def callback
    @client.code = params[:code]
    response = @client.fetch_access_token!
    session[:authorization] = response

    redirect_to  events_url
  end


  def events
    @client.update!(session[:authorization])

    service = Google::Apis::CalendarV3::CalendarService.new
    service.authorization = @client

    @owner_calendar = service.list_calendar_lists.items.select{ |calendar| calendar.access_role == 'owner' }.first
    @event_list = service.list_events(@owner_calendar.id)
  rescue Google::Apis::AuthorizationError
    response = @client.refresh!

    session[:authorization] = session[:authorization].merge(response)

    retry
  end

  private

    def set_client
      @client = Signet::OAuth2::Client.new(client_options)
    end

    def client_options
      {
          client_id: ENV['GOOGLE_CLIENT_ID'],
          client_secret: ENV['GOOGLE_CLIENT_SECRET'],
          authorization_uri: 'https://accounts.google.com/o/oauth2/auth',
          token_credential_uri: 'https://accounts.google.com/o/oauth2/token',
          scope: Google::Apis::CalendarV3::AUTH_CALENDAR,
          redirect_uri: ENV['RACK_ENV'] == 'production' ? 'https://desolate-beach-43675.herokuapp.com/callback' : 'http://localhost:3000/callback'
      }
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/calendars/events.html.haml
%h4= "Event list for current user <strong>#{current_user.email}</strong>".html_safe
%ul
- @event_list.items.each do |event|
  - if event.summary.present?
    %li
      %strong= 'Event location is:'
      #{event.location}
    %hr
    %li
      %strong= 'Start date:'
      #{event.start.date_time.strftime('%F %H:%M')}
    %li
      %strong= 'End date:'
      #{event.end.date_time.strftime('%F %H:%M')}
    %hr
    %li
      %strong= 'People who are attendees:'
    %ul
      - event.attendees.each do |a|
        %li
          %strong= 'Name: '
          #{a.display_name.present? ? a.display_name : a.email}
        %li= a.email
        %li
          %strong= a.response_status
        %hr
  %hr

app/views/home/index.html.haml
- if user_signed_in?
  %h4= link_to 'List of Owner Events', events_path
-else
  %h1 You are need to sign in before to see your events!

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title CalendarMeet
    = csrf_meta_tags
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar-inverse
      .navbar-header
        %button.navbar-toggle.collapsed{ aria: { expanded: 'false' }, data: { target: '#bs-navbar-collapse-1', toggle: 'collapse' }, type: 'button' }
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        = link_to 'Calendar meeting system', root_path, class: 'navbar-brand'
      #bs-navbar-collapse-1.collapse.navbar-collapse
        %ul.nav.navbar-nav
          %li
            = link_to 'Owner Events', events_path
        %ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            %li
              = link_to users_path() do
                %i.glyphicon.glyphicon-user
                = current_user.email
            %li
              = link_to destroy_user_session_path, method: :delete do
                %i.glyphicon.glyphicon-off
                = 'Logout'
          - else
            %li
              = link_to new_user_session_path do
                = 'Sign in'
            %li
              = link_to new_user_registration_path do
                = 'Sign up'
    .container-fluid
      .row{ style: 'padding-top: 100px;' }
        .col-sm-4.col-sm-offset-4
          = flash[:notice]
          = yield

app/views/users/index.html.haml
%ul
- @users.each do |user|
  %li
    = "Email: #{user.email}"